### PR TITLE
Fix v11.0.0 types that removed the default export

### LINKED ISSUE #1396: Broken type definition in focus-trap-react 11
**Description**
I am using ESM-style imports and exports in my project.

The change from `export = FocusTrap` to `export declare class FocusTrap` in [index.d.ts](https://github.com/focus-trap/focus-trap-react/commit/4a37daeade3c4d43da9e045441ff974d8acf1072#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8L4) means that it is now only possible to use _named_ imports, i.e. `import { FocusTrap } from "react-focus-trap"` (according to the types).

However, this is incompatible with `module.exports = FocusTrap;` in  [src/focus-trap-react.js](https://github.com/focus-trap/focus-trap-react/blob/4a37daeade3c4d43da9e045441ff974d8acf1072/src/focus-trap-react.js#L428), which only lets you do _default_ imports, i.e.  `import FocusTrap from "react-focus-trap"`.

So the type change needs to be reverted so only default imports works, or a named export should be provided instead:
```js
exports.FocusTrap = FocusTrap;
```

But that would obviously also be a breaking change. It is technically possible to hack it and provide both a named and default export with CJS:
```js
module.exports = FocusTrap;
module.exports.FocusTrap = FocusTrap;
```

**Versions**
- focus-trap-react version used: 11.0.0

**Sandbox**
Minimal reproduction in CodeSandbox should display the type error in the editor: https://codesandbox.io/p/sandbox/5fz5r4

**Local repro**
```bash
npm create vite@latest focus-trap-test -- --template react-ts
cd focus-trap-test
npm install focus-trap-react
# then edit `src/App.tsx` to add FocusTrap. If you have the TS language server running, your editor should highlight the error
```

### PR DESCRIPTION
**Pull request by stefcameron**
Fixes #1396

My original intent was to remove the default export (a breaking change) as part of the major 11.0.0 release but I totally flopped on that by not also actually providing the named export in the code.

Now that the major release ship has sailed, this change fixes the types by reinstating the default export in the typings but marking it deprecated, while also providing the new named export alternative as the way forward.

<details>
<summary>PR Checklist</summary>
<br/>

__Please leave this checklist in your PR.__

- Issue being fixed is referenced.
- Source changes maintain:
  - Stated browser compatibility.
  - Stated React compatibility.
- Web APIs introduced have __deep__ browser coverage, including Safari (often very late to adopt new APIs).
- Unit test coverage added/updated.
- E2E test coverage added/updated.
- Prop-types added/updated.
- Typings added/updated.
- Changes do not break SSR:
  - Careful to test `typeof document/window !== 'undefined'` before using it in code that gets executed on load.
- README updated (API changes, instructions, etc.).
- Changes to dependencies explained.
- Changeset added (run `npm run changeset` locally to add one, and follow the prompts).
  - EXCEPTION: A Changeset is not required if the change does not affect any of the source files that produce the package bundle. For example, demo changes, tooling changes, test updates, or a new dev-only dependency to run tests more efficiently should not have a Changeset since it will not affect package consumers.

</details>

### CODE REVIEW

**Comment by stefcameron** [comment]
This replaces #1397

File: index.d.ts [hunk 1]
```diff
@@ -1,14 +1,56 @@
 import { Options as FocusTrapOptions } from 'focus-trap';
 import * as React from 'react';
 
+export interface FocusTrapProps extends React.AllHTMLAttributes<any> {
```
Comment (Mathias-S) [inline index.d.ts:4]: Out of curiosity, why extend `React.AllHTMLAttributes` here? I know it was done in earlier releases as well, but as far as I can see, none of the normal HTML attributes get used for anything. For example if I use

```ts
<FocusTrap className="myFocusTrap">
  <div></div>
</FocusTrap>
```

Then the class name "myFocusTrap" doesn't get applied to any element.

Wouldn't it be better to remove this altogether?

```suggestion
export interface FocusTrapProps {
```

**Review by Mathias-S — COMMENTED** [review]
I've verified these changes to work as expected, both with the old default export, and with the new named export. The updated types also work.

However, I believe it would be an improvement to not extend `React.AllHTMLAttributes`, see comment.

File: index.d.ts (hunk 1 above)
Comment (stefcameron) [reply index.d.ts:4]: It's just been like that "forever" (before my time leading this project) but now that you point this out, you're totally right: There's no point in having this extension because `<FocusTrap>` doesn't render to anything, and doesn't reflect those extra HTML props onto anything either.

And it should be safe to remove that because setting something like `className` would have never done anything anyway, so I would expect nearly no one is doing this today anyway.

Comment (stefcameron) [reply index.d.ts]: @Mathias-S PR updated!

**Review by Mathias-S — APPROVED** [review]
These changes look good to me 🚀

**Comment by stefcameron** [comment]
@Mathias-S Thank you for your feedback! Merging and publishing.
